[package]
name = "turkiye-neu-ies-thesis-and-term-project"
version = "0.1.0"
entrypoint = "src/lib.typ"
authors = ["Ertuğrul UYAR <@ertugruluyar-github>"]
license = "MIT"
description = "Necmettin Erbakan Üniversitesi Eğitim Bilimleri Enstitiüsü lisansüstü eğitim için RESMÎ OLMAYAN tez önerisi, tez ve dönem projesi şablonudur. [Necmettin Erbakan University Institute of Educational Sciences is an UNOFFICIAL thesis proposal, thesis and term project template for graduate education.]"
repository = "https://github.com/ertugruluyar-github/turkiye-neu-ies-thesis"
categories = ["thesis", "report"]
keywords = [
    "thesis",
    "dissertation",
    "tez",
    "proposal",
    "öneri",
    "term project",
    "dönem projesi",
    "graduate education",
    "lisansüstü eğitim",
    "master",
    "yüksek lisans",
    "ph.d.",
    "PhD",
    "doctorate",
    "doktora",
    "university",
    "üniversite",
    "NEÜ",
    "Necmettin Erbakan",
    "eğitim bilimleri enstitüsü",
    "institute of educational sciences",
    "Türkiye",
]
compiler = "0.13.0"
exclude = [
    "thumbnails",
    "*.pdf",
]

[template]
path = "template"
entrypoint = "main.typ"
thumbnail = "thumbnails/thumbnail-1.png"